export enum ActionType {
  SET_LOTTO_DATA = 'SET_LOTTO_DATA',
  SET_LOTTO_DETAILS = 'SET_LOTTO_DETAILS',
  SET_SINGLE_SUM = 'SET_SINGLE_SUM',
  SET_LOADING = 'SET_LOADING',
  SET_DETAIL_ERROR = 'SET_DETAIL_ERROR',
}
